// GOS Route Master — 自動生成 (87路線)
export const ROUTE_MASTER = [
  {
    "route_id": 101,
    "name_ja": "山手線",
    "name_en": "Yamanote Line",
    "operator": "JR東日本",
    "line_code": "JY",
    "color": "#00AA00",
    "railway": "rail",
    "line_slug": "jr-east-yamanote",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 102,
    "name_ja": "中央線快速",
    "name_en": "Chuo Rapid Line",
    "operator": "JR東日本",
    "line_code": "JC",
    "color": "#FF6600",
    "railway": "rail",
    "line_slug": "jr-east-chuo-rapid",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 103,
    "name_ja": "中央・総武緩行線",
    "name_en": "Chuo-Sobu Line",
    "operator": "JR東日本",
    "line_code": "JB",
    "color": "#FCCC00",
    "railway": "rail",
    "line_slug": "jr-east-chuo-sobu",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 104,
    "name_ja": "京浜東北線",
    "name_en": "Keihin-Tohoku Line",
    "operator": "JR東日本",
    "line_code": "JK",
    "color": "#00BFFF",
    "railway": "rail",
    "line_slug": "jr-east-keihin-tohoku",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 105,
    "name_ja": "東海道線",
    "name_en": "Tokaido Line",
    "operator": "JR東日本",
    "line_code": "JT",
    "color": "#0066CC",
    "railway": "rail",
    "line_slug": "jr-east-tokaido",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 106,
    "name_ja": "横須賀線",
    "name_en": "Yokosuka Line",
    "operator": "JR東日本",
    "line_code": "JO",
    "color": "#0033CC",
    "railway": "rail",
    "line_slug": "jr-east-yokosuka",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 107,
    "name_ja": "総武快速線",
    "name_en": "Sobu Rapid Line",
    "operator": "JR東日本",
    "line_code": "JO",
    "color": "#CC9900",
    "railway": "rail",
    "line_slug": "jr-east-sobu-rapid",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 108,
    "name_ja": "上野東京ライン",
    "name_en": "Ueno-Tokyo Line",
    "operator": "JR東日本",
    "line_code": "UT",
    "color": "#0088CC",
    "railway": "rail",
    "line_slug": "jr-east-ueno-tokyo",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 109,
    "name_ja": "湘南新宿ライン",
    "name_en": "Shonan-Shinjuku Line",
    "operator": "JR東日本",
    "line_code": "SS",
    "color": "#CC3300",
    "railway": "rail",
    "line_slug": "jr-east-shonan-shinjuku",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 110,
    "name_ja": "埼京線",
    "name_en": "Saikyo Line",
    "operator": "JR東日本",
    "line_code": "JA",
    "color": "#00AA55",
    "railway": "rail",
    "line_slug": "jr-east-saikyo",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 111,
    "name_ja": "川越線",
    "name_en": "Kawagoe Line",
    "operator": "JR東日本",
    "line_code": "JKW",
    "color": "#339933",
    "railway": "rail",
    "line_slug": "jr-east-kawagoe",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 112,
    "name_ja": "武蔵野線",
    "name_en": "Musashino Line",
    "operator": "JR東日本",
    "line_code": "JM",
    "color": "#FF4500",
    "railway": "rail",
    "line_slug": "jr-east-musashino",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 113,
    "name_ja": "常磐線快速",
    "name_en": "Joban Rapid Line",
    "operator": "JR東日本",
    "line_code": "JJ",
    "color": "#009999",
    "railway": "rail",
    "line_slug": "jr-east-joban-rapid",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 114,
    "name_ja": "常磐線各駅停車",
    "name_en": "Joban Local Line",
    "operator": "JR東日本",
    "line_code": "JYB",
    "color": "#33CCCC",
    "railway": "rail",
    "line_slug": "jr-east-joban-local",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 115,
    "name_ja": "宇都宮線",
    "name_en": "Utsunomiya Line",
    "operator": "JR東日本",
    "line_code": "JU",
    "color": "#3399FF",
    "railway": "rail",
    "line_slug": "jr-east-utsunomiya",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 116,
    "name_ja": "高崎線",
    "name_en": "Takasaki Line",
    "operator": "JR東日本",
    "line_code": "JG",
    "color": "#0066FF",
    "railway": "rail",
    "line_slug": "jr-east-takasaki",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 117,
    "name_ja": "京葉線",
    "name_en": "Keiyo Line",
    "operator": "JR東日本",
    "line_code": "JE",
    "color": "#CC0033",
    "railway": "rail",
    "line_slug": "jr-east-keiyo",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 118,
    "name_ja": "南武線",
    "name_en": "Nambu Line",
    "operator": "JR東日本",
    "line_code": "JN",
    "color": "#FFCC00",
    "railway": "rail",
    "line_slug": "jr-east-nambu",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 119,
    "name_ja": "横浜線",
    "name_en": "Yokohama Line",
    "operator": "JR東日本",
    "line_code": "JH",
    "color": "#66CC33",
    "railway": "rail",
    "line_slug": "jr-east-yokohama",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 120,
    "name_ja": "鶴見線",
    "name_en": "Tsurumi Line",
    "operator": "JR東日本",
    "line_code": "JI",
    "color": "#999900",
    "railway": "rail",
    "line_slug": "jr-east-tsurumi",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 121,
    "name_ja": "青梅線",
    "name_en": "Omega Line",
    "operator": "JR東日本",
    "line_code": "JCW",
    "color": "#336600",
    "railway": "rail",
    "line_slug": "jr-east-omega",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 122,
    "name_ja": "五日市線",
    "name_en": "Itsukaichi Line",
    "operator": "JR東日本",
    "line_code": "JCW2",
    "color": "#336600",
    "railway": "rail",
    "line_slug": "jr-east-itsukaichi",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 123,
    "name_ja": "八高線",
    "name_en": "Hachiko Line",
    "operator": "JR東日本",
    "line_code": "JH2",
    "color": "#666600",
    "railway": "rail",
    "line_slug": "jr-east-hachiko",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 124,
    "name_ja": "成田線",
    "name_en": "Narita Line",
    "operator": "JR東日本",
    "line_code": "JR",
    "color": "#999933",
    "railway": "rail",
    "line_slug": "jr-east-narita",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 125,
    "name_ja": "総武本線",
    "name_en": "Sobu Main Line",
    "operator": "JR東日本",
    "line_code": "JB2",
    "color": "#996600",
    "railway": "rail",
    "line_slug": "jr-east-sobu-main",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 126,
    "name_ja": "武蔵野南線",
    "name_en": "Musashino South Line",
    "operator": "JR東日本",
    "line_code": "JM2",
    "color": "#FF6600",
    "railway": "rail",
    "line_slug": "jr-east-musashino-south",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 127,
    "name_ja": "東北貨物線",
    "name_en": "Tohoku Freight Line",
    "operator": "JR東日本",
    "line_code": "JFT",
    "color": "#444444",
    "railway": "rail",
    "line_slug": "jr-east-tohoku-freight",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 128,
    "name_ja": "中央本線",
    "name_en": "Chuo Main Line",
    "operator": "JR東日本",
    "line_code": "JCM",
    "color": "#FF6633",
    "railway": "rail",
    "line_slug": "jr-east-chuo-main",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 129,
    "name_ja": "相模線",
    "name_en": "Sagami Line",
    "operator": "JR東日本",
    "line_code": "JS",
    "color": "#6699CC",
    "railway": "rail",
    "line_slug": "jr-east-sagami",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 130,
    "name_ja": "内房線",
    "name_en": "Uchibo Line",
    "operator": "JR東日本",
    "line_code": "JUW",
    "color": "#CC6666",
    "railway": "rail",
    "line_slug": "jr-east-uchibo",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 131,
    "name_ja": "外房線",
    "name_en": "Sotobo Line",
    "operator": "JR東日本",
    "line_code": "JOS",
    "color": "#CC9999",
    "railway": "rail",
    "line_slug": "jr-east-sotobo",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 132,
    "name_ja": "久留里線",
    "name_en": "Kururi Line",
    "operator": "JR東日本",
    "line_code": "JRK",
    "color": "#996666",
    "railway": "rail",
    "line_slug": "jr-east-kururi",
    "operator_slug": "jr-east"
  },
  {
    "route_id": 201,
    "name_ja": "東急東横線",
    "name_en": "Tokyu Toyoko Line",
    "operator": "東急",
    "line_code": "TY",
    "color": "#CC0000",
    "railway": "rail",
    "line_slug": "tokyu-toyoko",
    "operator_slug": "tokyu"
  },
  {
    "route_id": 202,
    "name_ja": "東急目黒線",
    "name_en": "Tokyu Meguro Line",
    "operator": "東急",
    "line_code": "MG",
    "color": "#666666",
    "railway": "rail",
    "line_slug": "tokyu-meguro",
    "operator_slug": "tokyu"
  },
  {
    "route_id": 203,
    "name_ja": "東急田園都市線",
    "name_en": "Tokyu Denentoshi Line",
    "operator": "東急",
    "line_code": "DT",
    "color": "#228B22",
    "railway": "rail",
    "line_slug": "tokyu-denentoshi",
    "operator_slug": "tokyu"
  },
  {
    "route_id": 204,
    "name_ja": "東急大井町線",
    "name_en": "Tokyu Oimachi Line",
    "operator": "東急",
    "line_code": "OM",
    "color": "#CC6600",
    "railway": "rail",
    "line_slug": "tokyu-oimachi",
    "operator_slug": "tokyu"
  },
  {
    "route_id": 205,
    "name_ja": "東急世田谷線",
    "name_en": "Tokyu Setagaya Line",
    "operator": "東急",
    "line_code": "SG",
    "color": "#CC9966",
    "railway": "light_rail",
    "line_slug": "tokyu-setagaya",
    "operator_slug": "tokyu"
  },
  {
    "route_id": 206,
    "name_ja": "東急池上線",
    "name_en": "Tokyu Ikegami Line",
    "operator": "東急",
    "line_code": "IK",
    "color": "#CCAA66",
    "railway": "rail",
    "line_slug": "tokyu-ikegami",
    "operator_slug": "tokyu"
  },
  {
    "route_id": 207,
    "name_ja": "東急多摩川線",
    "name_en": "Tokyu Tamagawa Line",
    "operator": "東急",
    "line_code": "TM",
    "color": "#CCBB88",
    "railway": "rail",
    "line_slug": "tokyu-tamagawa",
    "operator_slug": "tokyu"
  },
  {
    "route_id": 208,
    "name_ja": "東急こどもの国線",
    "name_en": "Kodomono Kuni Line",
    "operator": "東急",
    "line_code": "KD",
    "color": "#99BB66",
    "railway": "rail",
    "line_slug": "tokyu-kodomono-kuni",
    "operator_slug": "tokyu"
  },
  {
    "route_id": 209,
    "name_ja": "京王線",
    "name_en": "Keio Line",
    "operator": "京王",
    "line_code": "KO",
    "color": "#CC0066",
    "railway": "rail",
    "line_slug": "keio-main",
    "operator_slug": "keio"
  },
  {
    "route_id": 210,
    "name_ja": "京王相模原線",
    "name_en": "Keio Sagamihara Line",
    "operator": "京王",
    "line_code": "KS",
    "color": "#990066",
    "railway": "rail",
    "line_slug": "keio-sagamihara",
    "operator_slug": "keio"
  },
  {
    "route_id": 211,
    "name_ja": "京王高尾線",
    "name_en": "Keio Takao Line",
    "operator": "京王",
    "line_code": "KT",
    "color": "#663366",
    "railway": "rail",
    "line_slug": "keio-takao",
    "operator_slug": "keio"
  },
  {
    "route_id": 212,
    "name_ja": "京王競馬場線",
    "name_en": "Keio Keibajo Line",
    "operator": "京王",
    "line_code": "KK",
    "color": "#CC6699",
    "railway": "rail",
    "line_slug": "keio-keibajo",
    "operator_slug": "keio"
  },
  {
    "route_id": 213,
    "name_ja": "京王動物園線",
    "name_en": "Keio Dobutsuen Line",
    "operator": "京王",
    "line_code": "KD2",
    "color": "#CC99AA",
    "railway": "rail",
    "line_slug": "keio-dobutsuen",
    "operator_slug": "keio"
  },
  {
    "route_id": 214,
    "name_ja": "井の頭線",
    "name_en": "Inokashira Line",
    "operator": "京王",
    "line_code": "IN",
    "color": "#33AA99",
    "railway": "rail",
    "line_slug": "keio-inokashira",
    "operator_slug": "keio"
  },
  {
    "route_id": 215,
    "name_ja": "小田急小田原線",
    "name_en": "Odawara Line",
    "operator": "小田急",
    "line_code": "OH",
    "color": "#3366CC",
    "railway": "rail",
    "line_slug": "odakyu-odawara",
    "operator_slug": "odakyu"
  },
  {
    "route_id": 216,
    "name_ja": "小田急江ノ島線",
    "name_en": "Enoshima Line",
    "operator": "小田急",
    "line_code": "OE",
    "color": "#3399CC",
    "railway": "rail",
    "line_slug": "odakyu-enoshima",
    "operator_slug": "odakyu"
  },
  {
    "route_id": 217,
    "name_ja": "小田急多摩線",
    "name_en": "Tama Line",
    "operator": "小田急",
    "line_code": "OT",
    "color": "#33CCCC",
    "railway": "rail",
    "line_slug": "odakyu-tama",
    "operator_slug": "odakyu"
  },
  {
    "route_id": 301,
    "name_ja": "東武伊勢崎線",
    "name_en": "Tobu Isesaki Line",
    "operator": "東武",
    "line_code": "TS",
    "color": "#CC0000",
    "railway": "rail",
    "line_slug": "tobu-isesaki",
    "operator_slug": "tobu"
  },
  {
    "route_id": 302,
    "name_ja": "東武東上線",
    "name_en": "Tobu Tojo Line",
    "operator": "東武",
    "line_code": "TJ",
    "color": "#0066CC",
    "railway": "rail",
    "line_slug": "tobu-tojo",
    "operator_slug": "tobu"
  },
  {
    "route_id": 303,
    "name_ja": "東武亀戸線",
    "name_en": "Tobu Kameido Line",
    "operator": "東武",
    "line_code": "TK",
    "color": "#CC6666",
    "railway": "rail",
    "line_slug": "tobu-kameido",
    "operator_slug": "tobu"
  },
  {
    "route_id": 304,
    "name_ja": "東武大師線",
    "name_en": "Tobu Daishi Line",
    "operator": "東武",
    "line_code": "TD",
    "color": "#996666",
    "railway": "rail",
    "line_slug": "tobu-daishi",
    "operator_slug": "tobu"
  },
  {
    "route_id": 305,
    "name_ja": "東武野田線",
    "name_en": "Tobu Urban Park Line",
    "operator": "東武",
    "line_code": "TN",
    "color": "#FF9900",
    "railway": "rail",
    "line_slug": "tobu-urban-park",
    "operator_slug": "tobu"
  },
  {
    "route_id": 306,
    "name_ja": "東武日光線",
    "name_en": "Tobu Nikko Line",
    "operator": "東武",
    "line_code": "TN2",
    "color": "#CC3300",
    "railway": "rail",
    "line_slug": "tobu-nikko",
    "operator_slug": "tobu"
  },
  {
    "route_id": 307,
    "name_ja": "東武宇都宮線",
    "name_en": "Utsunomiya Line",
    "operator": "東武",
    "line_code": "TU",
    "color": "#993333",
    "railway": "rail",
    "line_slug": "tobu-utsunomiya",
    "operator_slug": "tobu"
  },
  {
    "route_id": 308,
    "name_ja": "西武池袋線",
    "name_en": "Ikebukuro Line",
    "operator": "西武",
    "line_code": "SI",
    "color": "#0000CC",
    "railway": "rail",
    "line_slug": "seibu-ikebukuro",
    "operator_slug": "seibu"
  },
  {
    "route_id": 309,
    "name_ja": "西武新宿線",
    "name_en": "Shinjuku Line",
    "operator": "西武",
    "line_code": "SS2",
    "color": "#333399",
    "railway": "rail",
    "line_slug": "seibu-shinjuku",
    "operator_slug": "seibu"
  },
  {
    "route_id": 310,
    "name_ja": "西武拝島線",
    "name_en": "Haijima Line",
    "operator": "西武",
    "line_code": "SH",
    "color": "#666699",
    "railway": "rail",
    "line_slug": "seibu-haijima",
    "operator_slug": "seibu"
  },
  {
    "route_id": 311,
    "name_ja": "西武多摩湖線",
    "name_en": "Tamako Line",
    "operator": "西武",
    "line_code": "ST",
    "color": "#6699CC",
    "railway": "rail",
    "line_slug": "seibu-tamako",
    "operator_slug": "seibu"
  },
  {
    "route_id": 312,
    "name_ja": "西武狭山線",
    "name_en": "Sayama Line",
    "operator": "西武",
    "line_code": "SY",
    "color": "#6699AA",
    "railway": "rail",
    "line_slug": "seibu-sayama",
    "operator_slug": "seibu"
  },
  {
    "route_id": 313,
    "name_ja": "西武山口線",
    "name_en": "Leo Liner",
    "operator": "西武",
    "line_code": "LL",
    "color": "#FFCC00",
    "railway": "light_rail",
    "line_slug": "seibu-leo-liner",
    "operator_slug": "seibu"
  },
  {
    "route_id": 350,
    "name_ja": "京成線",
    "name_en": "Keisei Line",
    "operator": "京成",
    "line_code": "KS2",
    "color": "#0000AA",
    "railway": "rail",
    "line_slug": "keisei-main",
    "operator_slug": "keisei"
  },
  {
    "route_id": 351,
    "name_ja": "成田スカイアクセス",
    "name_en": "Skyliner Access",
    "operator": "京成",
    "line_code": "SA",
    "color": "#003399",
    "railway": "rail",
    "line_slug": "keisei-skyliner-access",
    "operator_slug": "keisei"
  },
  {
    "route_id": 352,
    "name_ja": "京急本線",
    "name_en": "Keikyu Main Line",
    "operator": "京急",
    "line_code": "KK2",
    "color": "#CC0033",
    "railway": "rail",
    "line_slug": "keikyu-main",
    "operator_slug": "keikyu"
  },
  {
    "route_id": 353,
    "name_ja": "京急空港線",
    "name_en": "Keikyu Airport Line",
    "operator": "京急",
    "line_code": "KA",
    "color": "#CC3366",
    "railway": "rail",
    "line_slug": "keikyu-airport",
    "operator_slug": "keikyu"
  },
  {
    "route_id": 354,
    "name_ja": "京急大師線",
    "name_en": "Daishi Line",
    "operator": "京急",
    "line_code": "KD3",
    "color": "#CC6699",
    "railway": "rail",
    "line_slug": "keikyu-daishi",
    "operator_slug": "keikyu"
  },
  {
    "route_id": 355,
    "name_ja": "京急逗子線",
    "name_en": "Zushi Line",
    "operator": "京急",
    "line_code": "KZ",
    "color": "#CC99AA",
    "railway": "rail",
    "line_slug": "keikyu-zushi",
    "operator_slug": "keikyu"
  },
  {
    "route_id": 356,
    "name_ja": "新京成線",
    "name_en": "Shinkeisei Line",
    "operator": "新京成",
    "line_code": "SK",
    "color": "#FF99CC",
    "railway": "rail",
    "line_slug": "shinkeisei-main",
    "operator_slug": "shinkeisei"
  },
  {
    "route_id": 357,
    "name_ja": "相鉄本線",
    "name_en": "Sotetsu Main Line",
    "operator": "相鉄",
    "line_code": "SO",
    "color": "#003399",
    "railway": "rail",
    "line_slug": "sotetsu-main",
    "operator_slug": "sotetsu"
  },
  {
    "route_id": 358,
    "name_ja": "相鉄いずみ野線",
    "name_en": "Izumino Line",
    "operator": "相鉄",
    "line_code": "SI2",
    "color": "#0066AA",
    "railway": "rail",
    "line_slug": "sotetsu-izumino",
    "operator_slug": "sotetsu"
  },
  {
    "route_id": 400,
    "name_ja": "銀座線",
    "name_en": "Ginza Line",
    "operator": "東京メトロ",
    "line_code": "G",
    "color": "#FF9500",
    "railway": "subway",
    "line_slug": "tokyo-metro-ginza",
    "operator_slug": "tokyo-metro"
  },
  {
    "route_id": 401,
    "name_ja": "丸ノ内線",
    "name_en": "Marunouchi Line",
    "operator": "東京メトロ",
    "line_code": "M",
    "color": "#F62E36",
    "railway": "subway",
    "line_slug": "tokyo-metro-marunouchi",
    "operator_slug": "tokyo-metro"
  },
  {
    "route_id": 402,
    "name_ja": "日比谷線",
    "name_en": "Hibiya Line",
    "operator": "東京メトロ",
    "line_code": "H",
    "color": "#B5B5AC",
    "railway": "subway",
    "line_slug": "tokyo-metro-hibiya",
    "operator_slug": "tokyo-metro"
  },
  {
    "route_id": 403,
    "name_ja": "東西線",
    "name_en": "Tozai Line",
    "operator": "東京メトロ",
    "line_code": "T",
    "color": "#009BBF",
    "railway": "subway",
    "line_slug": "tokyo-metro-tozai",
    "operator_slug": "tokyo-metro"
  },
  {
    "route_id": 404,
    "name_ja": "千代田線",
    "name_en": "Chiyoda Line",
    "operator": "東京メトロ",
    "line_code": "C",
    "color": "#00BB85",
    "railway": "subway",
    "line_slug": "tokyo-metro-chiyoda",
    "operator_slug": "tokyo-metro"
  },
  {
    "route_id": 405,
    "name_ja": "有楽町線",
    "name_en": "Yurakucho Line",
    "operator": "東京メトロ",
    "line_code": "Y",
    "color": "#C1A470",
    "railway": "subway",
    "line_slug": "tokyo-metro-yurakucho",
    "operator_slug": "tokyo-metro"
  },
  {
    "route_id": 406,
    "name_ja": "半蔵門線",
    "name_en": "Hanzomon Line",
    "operator": "東京メトロ",
    "line_code": "Z",
    "color": "#8F76D6",
    "railway": "subway",
    "line_slug": "tokyo-metro-hanzomon",
    "operator_slug": "tokyo-metro"
  },
  {
    "route_id": 407,
    "name_ja": "南北線",
    "name_en": "Namboku Line",
    "operator": "東京メトロ",
    "line_code": "N",
    "color": "#00AC9A",
    "railway": "subway",
    "line_slug": "tokyo-metro-namboku",
    "operator_slug": "tokyo-metro"
  },
  {
    "route_id": 408,
    "name_ja": "副都心線",
    "name_en": "Fukutoshin Line",
    "operator": "東京メトロ",
    "line_code": "F",
    "color": "#9C5E31",
    "railway": "subway",
    "line_slug": "tokyo-metro-fukutoshin",
    "operator_slug": "tokyo-metro"
  },
  {
    "route_id": 450,
    "name_ja": "都営浅草線",
    "name_en": "Asakusa Line",
    "operator": "都営地下鉄",
    "line_code": "A",
    "color": "#FF3377",
    "railway": "subway",
    "line_slug": "toei-asakusa",
    "operator_slug": "toei"
  },
  {
    "route_id": 451,
    "name_ja": "都営三田線",
    "name_en": "Mita Line",
    "operator": "都営地下鉄",
    "line_code": "I",
    "color": "#0066CC",
    "railway": "subway",
    "line_slug": "toei-mita",
    "operator_slug": "toei"
  },
  {
    "route_id": 452,
    "name_ja": "都営新宿線",
    "name_en": "Shinjuku Line",
    "operator": "都営地下鉄",
    "line_code": "S",
    "color": "#00CC66",
    "railway": "subway",
    "line_slug": "toei-shinjuku",
    "operator_slug": "toei"
  },
  {
    "route_id": 453,
    "name_ja": "都営大江戸線",
    "name_en": "Oedo Line",
    "operator": "都営地下鉄",
    "line_code": "E",
    "color": "#CC0099",
    "railway": "subway",
    "line_slug": "toei-oedo",
    "operator_slug": "toei"
  },
  {
    "route_id": 480,
    "name_ja": "ゆりかもめ",
    "name_en": "Yurikamome",
    "operator": "ゆりかもめ",
    "line_code": "U",
    "color": "#00AEEF",
    "railway": "light_rail",
    "line_slug": "yurikamome-main",
    "operator_slug": "yurikamome"
  },
  {
    "route_id": 481,
    "name_ja": "りんかい線",
    "name_en": "Rinkai Line",
    "operator": "東京臨海高速鉄道",
    "line_code": "R",
    "color": "#003399",
    "railway": "rail",
    "line_slug": "rinkai-main",
    "operator_slug": "rinkai"
  },
  {
    "route_id": 482,
    "name_ja": "多摩モノレール",
    "name_en": "Tama Monorail",
    "operator": "多摩都市モノレール",
    "line_code": "TM2",
    "color": "#FF9900",
    "railway": "monorail",
    "line_slug": "tama-monorail-main",
    "operator_slug": "tama-monorail"
  }
];
