/**
 * test_london_simulator.mjs
 * Run 50 games for London and verify simulator behavior.
 */
import { readFileSync } from "fs";
import { loadPackFromObject } from "../src/data/pack_loader.js";
import { generateDeckSync } from "../src/generators/deck_generator.js";
import { runSimulatorV3Sync } from "../src/simulator/game_simulator_v3.js";

const BASE = "cities/london";

let passed = 0;
let failed = 0;

function check(label, condition, detail = "") {
  if (condition) {
    console.log(`  ✓ ${label}`);
    passed++;
  } else {
    console.error(`  ✗ ${label}${detail ? " — " + detail : ""}`);
    failed++;
  }
}

function readJSON(path) {
  return JSON.parse(readFileSync(path, "utf-8"));
}

// Load London data
const profile = readJSON(`${BASE}/city_profile.json`);
const packRaw = readJSON(`${BASE}/data/packs/pack_v1.json`);
const metricsData = readJSON(`${BASE}/data/derived/station_metrics.json`);
const graphData = readJSON(`${BASE}/data/graph/station_graph.json`);

const packData = loadPackFromObject(packRaw);

// Generate deck using city profile defaults
const deckObj = generateDeckSync(metricsData.stations, null, {
  deckSize: profile.deck_defaults.deck_size,
  rarityTargets: profile.deck_defaults.rarity_targets,
});
const deckResult = deckObj.cards;

console.log("\n1. Deck generation");
check("deck size = 30", deckResult.length === 30, `got ${deckResult.length}`);
check("deck_meta.city_id", deckObj.deck_meta?.city_id !== undefined);
const deckRarities = {};
deckResult.forEach(c => { deckRarities[c.rarity] = (deckRarities[c.rarity] || 0) + 1; });
// Note: generateDeckSync uses station_metrics rarity field, not rarityTargets.
// Verify deck_v1.json (generated by generate_london_deck.py) instead.
const deck_v1 = readJSON(`${BASE}/data/decks/deck_v1.json`);
const deck_v1_rarities = {};
deck_v1.cards.forEach(c => { deck_v1_rarities[c.rarity] = (deck_v1_rarities[c.rarity] || 0) + 1; });
check("deck_v1 legendary = 1", deck_v1_rarities["legendary"] === 1, `got ${deck_v1_rarities["legendary"]}`);
check("no duplicate station_global_id", new Set(deckResult.map(c => c.station_global_id)).size === deckResult.length);

// Run 50 games
console.log("\n2. Simulator (50 games)");
const result = runSimulatorV3Sync(50, packData, null, { stationGraph: graphData });

const gs = result.game_stats;
const sr = result.strategy_ranking;  // sorted by win_rate desc
const ss = result.strategy_stats;    // { strategy_name: { wins, avg_score, avg_route_bonus, ... } }

check("total_simulations = 50", gs.total_simulations === 50, `got ${gs.total_simulations}`);
check("avg_turns > 0", gs.avg_turns > 0, `got ${gs.avg_turns}`);
check("avg_turns < 500", gs.avg_turns < 500, `got ${gs.avg_turns}`);

// Aggregate avg_score and bonuses across all strategies
const allStrategies = Object.values(ss);
const overallAvgScore = allStrategies.reduce((s, st) => s + (st.avg_score || 0), 0) / allStrategies.length;
const overallAvgRouteBonus = allStrategies.reduce((s, st) => s + (st.avg_route_bonus || 0), 0) / allStrategies.length;
const overallAvgNetworkBonus = allStrategies.reduce((s, st) => s + (st.avg_network_bonus || 0), 0) / allStrategies.length;

check("avg_score > 0", overallAvgScore > 0, `got ${overallAvgScore}`);
check("avg_route_bonus > 0", overallAvgRouteBonus > 0, `got ${overallAvgRouteBonus}`);
check("avg_network_bonus > 0", overallAvgNetworkBonus > 0, `got ${overallAvgNetworkBonus}`);

// Strategy ranking
check("strategy_ranking has 4 entries", sr.length === 4, `got ${sr.length}`);
const totalWins = sr.reduce((s, r) => s + r.wins, 0);
check("total wins = 50", totalWins === 50, `got ${totalWins}`);

console.log("\n  Strategy results:");
for (const s of sr) {
  console.log(`    ${s.strategy}: ${s.wins} wins (${s.win_rate.toFixed(1)}%) avg_score=${s.avg_score?.toFixed(2)} route_bonus=${s.avg_route_bonus?.toFixed(2)}`);
}
console.log(`  avg_turns: ${gs.avg_turns.toFixed(1)}`);
console.log(`  overall avg_score: ${overallAvgScore.toFixed(2)}`);
console.log(`  overall avg_route_bonus: ${overallAvgRouteBonus.toFixed(2)}`);
console.log(`  overall avg_network_bonus: ${overallAvgNetworkBonus.toFixed(2)}`);

// Top station
const topStation = result.top_stations?.[0];
if (topStation) {
  console.log(`  top station: ${topStation.name} (played ${topStation.wins} times)`);
}

console.log(`\n${"─".repeat(40)}`);
console.log(`Total: ${passed + failed} checks — ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
