// guno_v6/src/net/sync_protocol.js
// GUNO V6 Online Sync Protocol Definition
//
// Responsibility:
//   - Define the message types and payload shapes for online state sync
//   - Provide builder functions for each message type
//   - Provide a parser/validator for incoming messages
//
// Sync model: Host-Authoritative
//   - Host holds the canonical GameState
//   - Guests send ActionRequest messages
//   - Host processes actions, updates state, and broadcasts StateUpdate
//
// Rules:
//   - No DOM dependency
//   - Pure functions only

"use strict";

// ─────────────────────────────────────────
// Message types
// ─────────────────────────────────────────

export const MSG = {
  // Room management
  ROOM_JOIN:     "room:join",      // Guest → Host: join request
  ROOM_JOINED:   "room:joined",    // Host → Guest: join confirmed + player assignment
  ROOM_LEAVE:    "room:leave",     // Any → All: player leaving
  ROOM_READY:    "room:ready",     // Host → All: all players joined, game starting

  // Game actions (Guest → Host)
  ACTION_PLAY:   "action:play",    // Play a card
  ACTION_DRAW:   "action:draw",    // Draw a card
  ACTION_PASS:   "action:pass",    // Pass turn

  // State sync (Host → All)
  STATE_UPDATE:  "state:update",   // Full state broadcast after each action
  STATE_SYNC:    "state:sync",     // Full state resync (for reconnect)

  // Game lifecycle
  GAME_START:    "game:start",     // Host → All: game initialized
  GAME_OVER:     "game:over",      // Host → All: game ended with final scores
};

// ─────────────────────────────────────────
// Message builders
// ─────────────────────────────────────────

/**
 * Build a room:join message.
 * @param {string} roomId
 * @param {string} playerName
 * @returns {object}
 */
export function buildRoomJoin(roomId, playerName) {
  return { type: MSG.ROOM_JOIN, roomId, playerName, ts: Date.now() };
}

/**
 * Build a room:joined message (sent by host to the joining guest).
 * @param {string} roomId
 * @param {number} playerIndex - Assigned player index for the guest
 * @param {string[]} playerNames - All current player names
 * @returns {object}
 */
export function buildRoomJoined(roomId, playerIndex, playerNames) {
  return { type: MSG.ROOM_JOINED, roomId, playerIndex, playerNames, ts: Date.now() };
}

/**
 * Build an action:play message.
 * @param {number} playerIndex
 * @param {number} cardIndex
 * @returns {object}
 */
export function buildActionPlay(playerIndex, cardIndex) {
  return { type: MSG.ACTION_PLAY, playerIndex, cardIndex, ts: Date.now() };
}

/**
 * Build an action:draw message.
 * @param {number} playerIndex
 * @returns {object}
 */
export function buildActionDraw(playerIndex) {
  return { type: MSG.ACTION_DRAW, playerIndex, ts: Date.now() };
}

/**
 * Build an action:pass message.
 * @param {number} playerIndex
 * @returns {object}
 */
export function buildActionPass(playerIndex) {
  return { type: MSG.ACTION_PASS, playerIndex, ts: Date.now() };
}

/**
 * Build a state:update message (host → all, after each action).
 * @param {string} stateJSON - Serialized GameState (from serializers.stateToJSON)
 * @param {GameEvent[]} events - Events generated by the action
 * @returns {object}
 */
export function buildStateUpdate(stateJSON, events) {
  return { type: MSG.STATE_UPDATE, stateJSON, events, ts: Date.now() };
}

/**
 * Build a state:sync message (host → reconnecting guest).
 * @param {string} stateJSON
 * @returns {object}
 */
export function buildStateSync(stateJSON) {
  return { type: MSG.STATE_SYNC, stateJSON, ts: Date.now() };
}

/**
 * Build a game:start message.
 * @param {string} stateJSON - Initial GameState
 * @param {string[]} playerNames
 * @returns {object}
 */
export function buildGameStart(stateJSON, playerNames) {
  return { type: MSG.GAME_START, stateJSON, playerNames, ts: Date.now() };
}

/**
 * Build a game:over message.
 * @param {import("../core/scoring.js").ScoreBreakdown[]} scores
 * @returns {object}
 */
export function buildGameOver(scores) {
  return { type: MSG.GAME_OVER, scores, ts: Date.now() };
}

// ─────────────────────────────────────────
// Parser / validator
// ─────────────────────────────────────────

/**
 * Parse and validate an incoming message.
 * Returns null if the message is invalid.
 * @param {string|object} raw - Raw message (string or already-parsed object)
 * @returns {object|null}
 */
export function parseMessage(raw) {
  let msg;
  try {
    msg = typeof raw === "string" ? JSON.parse(raw) : raw;
  } catch {
    return null;
  }
  if (!msg || typeof msg.type !== "string") return null;
  if (!Object.values(MSG).includes(msg.type)) return null;
  return msg;
}

/**
 * @typedef {import("../core/game_engine.js").GameEvent} GameEvent
 */
